### ISSUE TITLE
CUKTIG are not "too far left"

### ISSUE THREAD

**Issue by fishface60** [andrew-t/tory-leadership-racer#1]
While I'd say CUKTIG are a right-wing party, going too far right wing as a Tory is not how you get there unless you ascribe to either horseshoe theory or signed integer overflow.

(the help text describes what happens if you go too far right wing twice when the intent is that CUKTIG are what happens to the left of the Tories)

**Comment by andrew-t** [comment]
Good catch! Fixed!

(There will be no silly political ideas like horseshoe theory or signed integer overflow in my Javascript world.)
